#!/usr/bin/env node
var exec = require("child_process").exec;
if(process.platform == "darwin") {
  exec(
    "./node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron ./ --verbose"
  );
}
