#!/usr/bin/env node
var exec = require("child_process").exec;
var platforms = {
  darwin: "./node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron ./ --verbose",
  linux: "./node_modules/electron-prebuilt/dist/electron ./ --verbose",
  win: ".\electron\electron.exe .\ --verbose"
}
if(process.platform == "darwin") {
  exec(platforms["darwin"]);
}else if(process.platform == "linux") {
  exec(platforms["linux"]);
}else if(/^win/.test(process.platform)) {
  exec(platforms["win"]);
}else{
  console.log("platform not supported");
}
